### ISSUE TITLE
brand/view/index/ link in product page

### ISSUE THREAD

**Issue by markdimi** [emizentech/magento2-shop-by-brand#18]
Why I am getting the above link in every product? 

![image](https://user-images.githubusercontent.com/5176216/39922563-535b038c-5528-11e8-966f-38421c6b6a07.png)

The link is applied to the "add item to basket", to the product counter, and the local area.

When I press "add to basket", or the `brand/view/index/` link the below happens:

`Fatal error: Uncaught Error: Call to a member function getAttributeId() on boolean in /var/www/html/vendor/emizentech/shopbybrand/Block/View.php:118 Stack trace: #0 /var/www/html/vendor/emizentech/shopbybrand/Block/View.php(58): Emizentech\ShopByBrand\Block\View->getProductCollection() #1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Emizentech\ShopByBrand\Block\View->__construct(Object(Magento\Catalog\Block\Product\Context), Object(Magento\Catalog\Model\ResourceModel\Product\CollectionFactory), Object(Magento\Catalog\Model\Product\Visibility), Object(Magento\Framework\App\Http\Context), Object(Emizentech\ShopByBrand\Model\BrandFactory), Array) #2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Emizentech\\Shop...', Array) #3 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Emizen in /var/www/html/vendor/emizentech/shopbybrand/Block/View.php on line 118`

Any ideas what is causing this?

**Comment by mpecoders** [comment]
There's a missing closing for <a> tag in product_brand.phtml
So here's the code should be

`<?php
$media = $this->getImageMediaPath();
$_fbrand = $block->getBrand();
?>
<span class="product-brand" style="float: left; clear: both; width: 100%;">
	<?php if($_fbrand->getUrlKey()):?>
		<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
	<?php else:?>
		<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
	<?php endif;?>
	<?php if($_fbrand->getLogo()):?>
		<img class="f-barnd-img" src="<?php echo $media.$_fbrand->getLogo() ?>" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>" style="height:40px"/>
	<?php else:?>
	<span class="brand-title">
		<?php echo $_fbrand->getName();?>
	</span>
	<?php endif;?>
</a>    
</span>
`

**Comment by emizentech** [comment]
Brand Logo & URL are updated in latest commit for this
