### ISSUE TITLE
Running into Array To String Conversion error on M2

### ISSUE THREAD

**Issue by ipekerti** [emizentech/magento2-shop-by-brand#2]
Hello,

We're implementing an M2 CE (2.0.4), and using your ShopByBrand extension.  We are running into array to string conversion error when attempting to disable the Featured setting.  I think we were able to change the setting for 1 single brand.

We have about 167 brand records, all have images associated to them.  The record ID ranges from 1432-1598.

I'm attaching the error log displayed after hitting the SAVE button.

Can you help?  Are we doing something wrong?

Thanks in advance.
Immanuel Pekerti
Specialized Products Company

[ShopByBrand-ErrLog.txt](https://github.com/emizentech/magento2-shop-by-brand/files/211556/ShopByBrand-ErrLog.txt)

**Comment by friizu** [comment]
hei, this seems to be same error i fixed here;
https://github.com/emizentech/magento2-shop-by-brand/issues/3

**Comment by emizentech** [comment]
resolved in latest commit 
kindly pull latest files
