### ISSUE TITLE
Save image

### ISSUE THREAD

**Issue by friizu** [emizentech/magento2-shop-by-brand#3]
Hei

Right now u cant save new image before u have deleted old one, also if u allready have image u get php notice (in dev mode) ... so on save.php (line 50) probably should be something like:

`//unset($data['image']);`
`
	if (isset($data['logo']['value'])) {
	$data['logo'] = $data['logo']['value'];
	} else {
	$data['logo'] = null;
}`

**Comment by emizentech** [comment]
resolved in latest commit 
kindly pull latest files
