### ISSUE TITLE
Product with status disabled

### ISSUE THREAD

**Issue by friizu** [emizentech/magento2-shop-by-brand#4]
Hei again, tnx for nice module ;)

Found a small bug:
When open single brand to view products, it also **shows out products with status set disabled**.

And some other questions.

1. Is there a way to show brand logo on single product page? (Magento_Catalog/layout/catalog_product_view.xml)
2. Brand page shows all products connected to this brand, is there a easy way to show products like in category pages - "Products per Page on Grid" , so there will be pagination and sorting options.

**Comment by emizentech** [comment]
Brand Logo / Name & Link has been added to product page 
Status Filter is also added 
kindly refer to latest commit
