### ISSUE TITLE
Can't see add button to create brand

### ISSUE THREAD

**Issue by Dayssam** [emizentech/magento2-shop-by-brand#5]
Hi everyone,

Thanks for the free module & the nice work

I cant find the create button to create a brand

![brand](https://cloud.githubusercontent.com/assets/13301885/15368044/cb870ebc-1d23-11e6-82e2-9ac6b502490b.png)

Thanks in advance

**Comment by emizentech** [comment]
its assiciated with default manufacturer attribute
you need to add options of that attribute and click Re-Sync Button 
your new options will be here
