### ISSUE TITLE
shows products with visibility set to 'Not Visible Individually'

### ISSUE THREAD

**Issue by sscraggles** [emizentech/magento2-shop-by-brand#6]
I have lots of simple products set as "Not Visible Individually" for inclusion in Configurable and Bundle products.

When viewing the individual brand page, all the products set as Not Visible are displayed.  Can this be fixed so Not Visible products are *not* displayed?

**Comment by emizentech** [comment]
resolved in latest commits

**Comment by sscraggles** [comment]
That's awesome, thankyou so much.  You guys will be my first choice if I ever need any custom work done.
